spring:
  application:
    name: manoexperta
  datasource: 
    driverClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://google/db_dev_manoexperta?cloudSqlInstance=dev-manoexperta-206420:us-central1:db-dev-manoexperta&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=root&password=root"
    password: "root"
    username: "root"
    testOnBorrow: true
    testWhileIdle: true
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000